<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>TradeCraft</title>
  <link rel="stylesheet" href="css/style.css" />
</head>
<body>
  <header>
    <h1>TradeCraft</h1>
    <nav>
      <a href="index.html">Home</a>
      <a href="strategies.html">Strategies</a>
      <a href="notes.html">Notes</a>
    </nav>
  </header>

  <main>
    <section class="video-section">
      <h2>Pro Trader Videos</h2>
      <div class="video-grid">
        <iframe src="https://www.youtube.com/embed/2e4d3I1vJ0g" frameborder="0" allowfullscreen></iframe>
        <iframe src="https://www.youtube.com/embed/1YyAzVmP3v0" frameborder="0" allowfullscreen></iframe>
        <iframe src="https://www.youtube.com/embed/3nJ1N1U1z1A" frameborder="0" allowfullscreen></iframe>
      </div>
    </section>
  </main>

  <footer>
    <p>© 2025 TradeCraft. Built for day traders, by day traders.</p>
  </footer>
</body>
</html>
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: 'Share Tech Mono', monospace;
  background-color: #0a0a0a;
  color: #f0f0f0;
  line-height: 1.6;
}

header {
  background-color: #111;
  padding: 20px;
  text-align: center;
  border-bottom: 2px solid #444;
}

header h1 {
  font-size: 2.5rem;
  letter-spacing: 2px;
}

nav {
  margin-top: 10px;
}

nav a {
  color: #f0f0f0;
  margin: 0 15px;
  text-decoration: none;
  font-weight: bold;
  transition: color 0.3s;
}

nav a:hover {
  color: #00ffe7;
}

.video-section {
  padding: 40px 20px;
  text-align: center;
}

.video-section h2 {
  font-size: 2rem;
  margin-bottom: 20px;
}

.video-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 20px;
  padding: 0 10px;
}

iframe {
  width: 100%;
  height: 200px;
  border: 2px solid #333;
  border-radius: 8px;
}

footer {
  background-color: #111;
  text-align: center;
  padding: 20px;
  border-top: 2px solid #444;
  font-size: 0.9rem;
}
git checkout -b retry-deploy
git add .
git commit -m "Retry deploy with clean base"
git push origin retry-deploy
